#Templated service configuration file
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: phpmyadmin

---

#Templated deployment configuration file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      run: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        run: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never #Take local image, do not pull from online
        ports:
        - containerPort: 5000
