#YALM is a language used as a format for configuration files, it builds objects like for kubernetes a deployment or service object
#Indentation (non-tab) is used to structure the code
#imagePullPolicy means allowing to pull online image or take image locally
#80 -> http, 443 -> ssl, 22 -> ssh

#Templated service configuration file
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 22
    targetPort: 22
    name: ssh
  type: LoadBalancer
  selector:
    app: nginx

---

#Templated deployment configuration file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
