---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - $(minikube ip) #Create a c program that will write at end of file the address ip, or maybe use a shell command in yalm file
