#Templated service configuration file
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  ports:
    - port: 21
      targetPort: 21
  type: LoadBalancer
  selector:
    app: ftps

---

#Templated deployment configuration file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      run: ftps
  replicas: 1
  template:
    metadata:
      labels:
        run: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
